/****************************************************************************
 JSCommunicator
 http://jscommunicator.org

 Copyright (C) 2013  Daniel Pocock http://danielpocock.com

 The JavaScript code in this page is free software: you can
 redistribute it and/or modify it under the terms of the GNU
 General Public License (GNU GPL) as published by the Free Software
 Foundation, either version 2 of the License, or (at your option)
 any later version.  The code is distributed WITHOUT ANY WARRANTY;
 without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU GPL for more details.

 You may distribute non-source (e.g., minimized or compacted) forms of
 that code without the full copy of the GNU GPL normally required
 provided you include this license notice and a URL
 through which recipients can access the Corresponding Source.
****************************************************************************/

(function(a){window.JSCommManager={currentURL:null,phone:null,current_session:null,first_run:!0,credentials:{display_name:null,uri:null,sip_auth_user:null,sip_auth_password:null,sip_auth_user_full_uri:!0},init:function(){window.console||(window.console={});window.console.log||(window.console.log=function(){});window.console.error||(window.console.error=function(){});if(WebRTCSupported()){if(!window.JSCommSettings)return JSCommUI.show_error("no-config"),Arbiter.publish("jsc/unavailable/config",null,
{async:!0}),!1;this.currentURL=parseUri(window.location.toString());if(this.currentURL.queryKey.dial){var b=JSCommSettings.dialing.auto_dial.use_video;this.currentURL.queryKey.video&&(b=a.parseJSON(decodeURIComponent(this.currentURL.queryKey.video)));JSCommSettings.dialing.auto_dial={default_destination:decodeURIComponent(this.currentURL.queryKey.dial),on_startup:!0,use_video:b}}this.credentials=JSCommSettings.user;this.start_ua()}else JSCommUI.show_error("webrtc"),Arbiter.publish("jsc/unavailable/webrtc",
null,{async:!0})},start_login:function(){JSCommUI.show_login()},start_ua:function(){var a=!1;this.credentials.uri&&this.credentials.sip_auth_password&&(a=!0);if(a){if(!this.credentials.sip_auth_user||0==this.credentials.sip_auth_user.length)this.credentials.sip_auth_user_full_uri?this.credentials.sip_auth_user=this.credentials.uri.substr(4):(a=this.credentials.uri.indexOf("@")-4,this.credentials.sip_auth_user=this.credentials.uri.substr(4,a)),console.log("auth username has been automatically derived from the user SIP address: "+
this.credentials.uri+" => "+this.credentials.sip_auth_user);a=JSCommSettings.turn_servers;if("[object Array]"===Object.prototype.toString.call(a))for(var c=0;c<a.length;c++){if(!a[c].username||0==a[c].username.length)a[c].username=this.credentials.sip_auth_user,a[c].password=this.credentials.sip_auth_password}else if(!a.username||0==a.username.length)a.username=this.credentials.sip_auth_user,a.password=this.credentials.sip_auth_password;JSCommSettings.user=this.credentials;try{this.JsSIPSettings=
getJsSIPSettings(JSCommSettings),this.phone=new JsSIP.UA(this.JsSIPSettings)}catch(d){return console.log(d.toString()),JSCommUI.show_error("ua-init-failure"),!1}JSCommUI.init();this.phone.on("connected",function(a){JSCommManager.link_up()});this.phone.on("disconnected",function(a){JSCommManager.link_down()});this.phone.on("registered",function(a){JSCommManager.registration_up()});this.phone.on("unregistered",function(a){JSCommManager.registration_down()});this.phone.on("registrationFailed",function(a){console.log("Registration failure: "+
a.toString());JSCommManager.registration_failure()});this.phone.on("newRTCSession",function(a){JSCommManager.session_start(a)});this.phone.on("newTransaction",function(a){console.log("newTransaction");var b=a.data.transaction;if(b&&b.request_sender&&b.request_sender.applicant&&"outgoing"==b.request_sender.applicant.direction){if(console.log("outgoing call"),(a=b.request)&&a.method&&"INVITE"==a.method&&a.body){var c=a.body.search("typ relay");0>c&&(console.log("No relay candidate found in SDP"),JSCommSettings.session.require_relay_candidate&&
(console.log("require_relay_candidate is set yet no relay candidate found, call prohibited"),b.onTransportError(),Arbiter.publish("jsc/unavailable/relay",null,{async:!0})));c=a.body.search("a=crypto");console.log("pos = "+c);0>c&&(console.log("Doing workaround for Asterisk issue 22961"),b=a.body.replace(/ RTP/g," UDP/TLS/RTP"),a.body=b)}}else if(b&&(a=b.request)&&a.method&&"INVITE"==a.method&&a.body)console.log("fixing incoming SDP if necessary..."),b=a.body.replace(/ UDP.TLS.RTP/g," RTP"),a.body=
b});this.phone.on("newMessage",function(a){JSCommManager.message_received(a)});Arbiter.subscribe("jsc/destination/set",{async:!0},function(a){JSCommManager.set_destination(a)});this.phone.start()}else JSCommUI.init(),this.start_login()},init_first_connection:function(){console.log("First connection");this.first_run=!1;var a=JSCommSettings.dialing.auto_dial.default_destination;if(a){this.set_destination(a);var c=JSCommSettings.dialing.auto_dial.use_video;JSCommSettings.dialing.auto_dial.on_startup&&
this.make_call(a,c)}else JSCommUI.set_destination("",!1,!0)},set_destination:function(a){JSCommUI.set_destination(a,!JSCommSettings.dialing.edit_destination,JSCommSettings.dialing.show_destination)},link_up:function(){JSCommUI.link_up();this.first_run&&this.init_first_connection();Arbiter.publish("jsc/ua/idle",null,{async:!0})},link_down:function(){JSCommUI.link_down();Arbiter.publish("jsc/ua/notready",null,{async:!0})},registration_up:function(){JSCommUI.registration_up()},registration_down:function(){JSCommUI.registration_down()},
registration_failure:function(){JSCommUI.registration_failure()},session_start:function(a){var c=a.data.session;if(null!=this.current_session)console.log("rejecting new session, a session is already active"),c.terminate();else{this.current_session=c;Arbiter.publish("jsc/ua/incall",null,{async:!0});var d=c.remote_identity.uri.toAor().toString();a="<"+d+">";c.remote_identity.display_name&&(a=c.remote_identity.display_name+" "+a);console.log("peer_name: "+a);var e;"incoming"===c.direction?(e="incoming",
Arbiter.publish("jsc/call/incoming",d,{async:!0})):(e="trying",Arbiter.publish("jsc/call/outgoing",d,{async:!0}));d=0<c.getLocalStreams().length&&0<c.getLocalStreams()[0].getVideoTracks().length||0<c.getRemoteStreams().length&&0<c.getRemoteStreams()[0].getVideoTracks().length;JSCommUI.session_start(e,a,d);c.on("progress",function(a){JSCommUI.session_progress("incoming"===c.direction?"incoming":"trying")});c.on("failed",function(a){JSCommUI.session_failed(a.data.cause);delete JSCommManager.current_session;
Arbiter.publish("jsc/call/failed",null,{async:!0});Arbiter.publish("jsc/ua/idle",null,{async:!0})});c.on("started",function(a){JSCommUI.session_connect(c,a);Arbiter.publish("jsc/call/connected",null,{async:!0})});c.on("newDTMF",function(a){"remote"===a.data.originator&&(dtmf_char=a.data.dtmf.tone,JSCommUI.incoming_dtmf(dtmf_char),Arbiter.publish("jsc/call/dtmf",dtmf_char,{async:!0}))});c.on("ended",function(a){JSCommUI.session_end();delete JSCommManager.current_session;Arbiter.publish("jsc/call/end",
null,{async:!0});Arbiter.publish("jsc/ua/idle",null,{async:!0})})}},message_received:function(a){console.log("received message, not handled: "+a)},register:function(){this.phone.register()},deregister:function(){this.phone.unregister()},make_call:function(a,c){try{var d=[];JSCommSettings.extra_headers&&(d=JSCommSettings.extra_headers);this.phone.call(a,{mediaConstraints:{audio:!0,video:c},RTCConstraints:{optional:[{DtlsSrtpKeyAgreement:"true"}]},turn_servers:this.JsSIPSettings.turn_servers,extraHeaders:d})}catch(e){JSCommUI.show_error_tmp("call-attempt-failed"),
console.log("make_call failed: "+e.toString()),console.log(e)}},cancel_call:function(){this.current_session.terminate()},reject_call:function(){this.current_session.terminate()},answer_call:function(a){this.current_session.answer({mediaConstraints:{audio:!0,video:a}})},hangup_call:function(){this.current_session.terminate()},send_dtmf:function(a){var c=100;JSCommSettings.session.dtmf_duration&&(c=JSCommSettings.session.dtmf_duration);this.current_session.sendDTMF(a,{duration:c})}}})(jQuery);
(function(a){window.JSCommUI={soundPlayer:null,soundLoop:null,url_prefix:"",init_done:!1,init:function(){this.init_done?console.log("JSCommUI.init() called more than once"):(console.log("starting init"),a("#network-controls #error #js").hide(),JSCommSettings.webserver.url_prefix&&(this.url_prefix=JSCommSettings.webserver.url_prefix),JSCommUI.link_down(),soundPlayer=document.createElement("audio"),a("#jsc-login-display-name-field").keypress(function(b){13==b.which&&a("#jsc-login-sip-address-field").focus()}),
a("#jsc-login-sip-address-field").keypress(function(b){13==b.which&&a("#jsc-login-password-field").focus()}),a("#jsc-login-password-field").keypress(function(a){13==a.which&&JSCommUI.do_login()}),a("#reg-button").click(function(){JSCommManager.register()}),a("#de-reg-button").click(function(){JSCommManager.deregister()}),a("#dest #address").keypress(function(a){13==a.which&&JSCommUI.make_call(JSCommSettings.dialing.prefer_video)}),a("#call-audio").click(function(){JSCommUI.make_call(!1)}),a("#call-video").click(function(){JSCommUI.make_call(!0)}),
a("#session-cancel").click(function(){JSCommManager.cancel_call()}),a("#session-reject").click(function(){JSCommManager.reject_call()}),a("#session-answer").click(function(){JSCommUI.answer_call(!1)}),a("#session-answer-video").click(function(){JSCommUI.answer_call(!0)}),a("#session-hangup").click(function(){JSCommManager.hangup_call()}),a("#dtmf-pad input:button").click(function(){var b=a(this).val();JSCommUI.send_dtmf(b)}),a("#video-control-self-view").click(function(){JSCommUI.self_view(!0)}),
a("#video-control-self-hide").click(function(){JSCommUI.self_view(!1)}),a("#video-control-fullscreen").click(function(){JSCommUI.video_fullscreen(!0)}),JSCommSettings.registration.user_control||a("#reg #control").hide(),this.init_done=!0)},show_login:function(){a("#jsc-login-display-name-field").val(JSCommManager.credentials.display_name);4<JSCommManager.credentials.uri.length&&a("#jsc-login-sip-address-field").val(JSCommManager.credentials.uri.substr(4));a("#jsc-login-password-field").val(JSCommManager.credentials.sip_auth_password);
a("#jsc-login").show();a("#jsc-login-button").click(JSCommUI.do_login)},do_login:function(){a("#jsc-login").hide();JSCommManager.credentials.display_name=a("#jsc-login-display-name-field").val();JSCommManager.credentials.uri="sip:"+a("#jsc-login-sip-address-field").val();JSCommManager.credentials.sip_auth_password=a("#jsc-login-password-field").val();JSCommManager.start_ua()},show_error:function(b){a("#network-controls #error #js").hide();a("#network-controls #error #"+b).show()},show_error_tmp:function(b){a("#network-controls #error #js").hide();
a("#network-controls #error #"+b).show();a("#network-controls #error #"+b).fadeTo(5E3,1,function(){a(this).hide()})},set_link_state:function(b){a("#network-controls #ws").show();a("#network-controls #ws .state").hide();b?(a(".ws-disconnected").hide(),a("#network-controls #ws #connected").show()):(a(".ws-connected").hide(),a("#network-controls #ws #disconnected").show())},ready_to_dial:function(){a("#dial-controls").show();a("#dialing-actions input:button").hide();JSCommSettings.dialing.audio_dialing&&
a("#dialing-actions #call-audio").show();JSCommSettings.dialing.video_dialing&&a("#dialing-actions #call-video").show();a("#dest #address").focus()},make_call:function(b){var c=a("#address").val();1>c.length?console.log("no destination specified, can't make call"):JSCommManager.make_call(c,b)},answer_call:function(b){clearInterval(JSCommUI.soundLoop);soundPlayer.pause();a("#session-controls #state span").hide();a("#session-controls #state .session-accepted").show();a("#session-actions input:button").hide();
JSCommManager.answer_call(b)},set_destination:function(b,c,d){a("#address").val(b);a("#address").attr("disabled",c);d&&a("#dest").show()},incoming_dtmf:function(a){this.play_dtmf_sound(a)},link_up:function(){JSCommUI.set_link_state(!0);JSCommUI.ready_to_dial()},link_down:function(){JSCommUI.set_link_state(!1)},registration_up:function(){a("#network-controls #error #reg-fail").hide();a("#network-controls #reg .down").hide();a("#network-controls #reg .up").show();a("#network-controls #reg").show()},
registration_down:function(){a("#network-controls #reg .up").hide();a("#network-controls #reg .down").show();a("#network-controls #reg").show()},registration_failure:function(){a("#network-controls #error #reg-fail").show();a("#network-controls #reg").show()},play_again:function(){soundPlayer.play()},session_start:function(b,c,d){a("#dial-controls").hide();a(".session-active").hide();a("#session-controls #state span").hide();a("#session-controls #peer").empty();a("#session-controls #peer").text(c);
a("#session-actions input:button").hide();"incoming"==b?(a("#session-controls #state .session-incoming").show(),a("#session-actions input.session-incoming:button").show(),soundPlayer.setAttribute("src",this.get_sound_url("incoming-call2")),soundPlayer.play(),clearInterval(JSCommUI.soundLoop),JSCommUI.soundLoop=setInterval(JSCommUI.play_again,3E3)):"trying"==b?(a("#session-controls #state .session-outgoing").show(),a("#session-actions input.session-outgoing:button").show()):console.log("Unexpected status: "+
b);a("#session-controls").show();d&&(a("#video-session").show(),JSCommUI.self_view(!0))},session_failed:function(b){clearInterval(JSCommUI.soundLoop);soundPlayer.pause();b?(a("#network-controls #error #dynamic").empty(),a("#network-controls #error #dynamic").append(b),this.show_error_tmp("dynamic")):this.show_error_tmp("call-attempt-failed");soundPlayer.setAttribute("src",this.get_sound_url("outgoing-call-rejected"));soundPlayer.play();this.session_cleanup()},session_cleanup:function(){clearInterval(JSCommUI.soundLoop);
soundPlayer.pause();a("#session-controls").hide();a("#video-session").hide();JSCommUI.ready_to_dial()},session_progress:function(a){"trying"==a&&(console.log("starting ringback..."),soundPlayer.setAttribute("src",this.get_sound_url("outgoing-call2")),soundPlayer.play(),clearInterval(JSCommUI.soundLoop),JSCommUI.soundLoop=setInterval(JSCommUI.play_again,5E3))},session_connect:function(b,c){clearInterval(JSCommUI.soundLoop);soundPlayer.pause();a("#session-controls #state span").hide();a("#session-controls .session-active").show();
JSCommSettings.session.show_dtmf_pad?a("#session-controls #dtmf-pad").show():a("#session-controls #dtmf-pad").hide();a("#session-actions input:button").hide();a("#session-actions input.session-active:button").show();var d=b.getLocalStreams().length,e=b.getRemoteStreams().length;console.log("local stream count = "+d+", remote stream count = "+e);0<d&&(a("#selfView").attr("src",window.URL.createObjectURL(b.getLocalStreams()[0])),a("#selfView").attr("volume",0));0<e&&a("#remoteView").attr("src",window.URL.createObjectURL(b.getRemoteStreams()[0]));
0<d&&0<b.getLocalStreams()[0].getVideoTracks().length||0<e&&0<b.getRemoteStreams()[0].getVideoTracks().length?(a("#video-session").show(),JSCommUI.self_view(!0)):a("#video-session").hide()},session_end:function(){this.session_cleanup()},send_dtmf:function(a){console.log("DTMF press: "+a);JSCommManager.send_dtmf(a);this.play_dtmf_sound(a)},self_view:function(b){a("#video-controls input.self:button").hide();b?(a("#video-control-self-hide").show(),a("#video-session #selfView").show()):(a("#video-control-self-view").show(),
a("#video-session #selfView").hide())},video_fullscreen:function(b){b?(console.log("Going fullscreen..."),a("#video-session").attr("class","full-screen")):(console.log("Leaving fullscreen..."),a("#video-session").attr("class",""))},get_sound_url:function(a){return this.url_prefix+"sounds/"+a+".ogg"},play_dtmf_sound:function(a){var c=a;"*"==a?c="asterisk":"#"==a&&(c="hash");console.log("Playing sound: "+c);soundPlayer.setAttribute("src",this.get_sound_url("dialpad/"+c));soundPlayer.play()}}})(jQuery);
function getJsSIPSettings(a){var b=a.turn_servers,c=[];if("[object Array]"===Object.prototype.toString.call(b))for(var d=0;d<b.length;d++)c[d]={},c[d].urls=b[d].server,c[d].username=b[d].username,c[d].password=b[d].password;else c[0].urls=b.server,c[0].username=b.username,c[0].password=b.password;return{uri:a.user.uri,password:a.user.sip_auth_password,ws_servers:a.websocket.servers,display_name:a.user.display_name,authorization_user:a.user.sip_auth_user,register:a.registration.on_startup,register_expires:a.registration.expiry,
registrar_server:a.registration.server,no_answer_timeout:a.dialing.no_answer_timeout,trace_sip:!0,stun_servers:a.stun_servers,turn_servers:c,use_preloaded_route:!1,connection_recovery_min_interval:a.websocket.connection_recovery_min_interval,connection_recovery_max_interval:a.websocket.connection_recovery_max_interval,hack_via_tcp:!1,hack_ip_in_contact:!1}}
function parseUri(a){var b=parseUri.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},d=14;d--;)c[b.key[d]]=a[d]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(a,d,f){d&&(c[b.q.name][d]=f)});return c}
parseUri.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};
function WebRTCSupported(){if(navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.getUserMedia)return!0;console.error("WebRTC support not found");return!1};
